### ISSUE TITLE
Question: Uninstall MIRO

### ISSUE THREAD

**Issue by yordiak** [GAMS-dev/miro#10] opened 2020-08-01 13:16 UTC
How can I uninstall MIRO in a Windows 10 64bit machine? Thanks in advance

**Comment by rschuchmann** [comment] 2020-08-04 08:49
You can uninstall GAMS MIRO like any other software:

1. Start Settings from the Start menu.
2. Click "Apps."
3. In the pane on the left, click "Apps & features." 
4. In the Apps & features pane on the right, find GAMS MIRO and click on it. 
5. Windows will uninstall the program.

**Comment by yordiak** [comment] 2020-08-04 10:08
Unfortunately, this does not work for me. When I try to uninstall GAMS MIRO 1.0.0 I get the following error

`Windows cannot find 'C\Users\username\AppData\Local\Programs\GAMS MIRO\Uninstall GAMS MIRO.exe`

This is the default installation path of GAMS MIRO, which I have not modify it. For some reason it seems that Uninstall GAMS MIRO.exe is skipped through installation process.

I get the same error when I try to uninstall GAMS MIRO 1.1.1

**Comment by yordiak** [comment] 2020-08-04 10:20
I managed to uninstall it by forcing an uninstalling process through a special software, like wise program uninstaller. However, I believe that this is not an intended behavior (i.e. to be able to uninstall MIRO onlty through specialiazed softwares)

**Comment by rschuchmann** [comment] 2020-08-04 11:14
This is indeed not the intended behavior. Actually, the [above steps](https://github.com/GAMS-dev/miro/issues/10#issuecomment-668470424) should do the job. We'll look into it. Do you have any ideas on how we can reproduce this? Did you notice anything during the installation?

**Comment by yordiak** [comment] 2020-08-04 11:58
The above steps work only if the Uninstall GAMS MIRO.exe exists in the first place. The only way you can reproduce is to try to install MIRO in a win64 machine and then to try to uninstall it. 

Nothing weird happened through the installation process, nor did I change any default option. The same problem appears in the latest version, 1.1.1, which also is not possible to be uninstalled by following your steps

**Comment by rschuchmann** [comment] 2020-08-04 12:40
Ok, thanks. I cannot reproduce this, but I will keep an eye on it.

**Comment by yordiak** [comment] 2020-08-04 12:44
the default installation path is C\Users\username\AppData\Local\Programs\
 I don't know if the problem is related to this path

**Comment by rschuchmann** [comment] 2020-08-04 12:59
> the default installation path is C\Users\username\AppData\Local\Programs  

This is the commonly used default path on Windows for software that is installed for only one user. If you select to install GAMS MIRO for 'all users', it will be in `C:\Program Files\GAMS MIRO`. 

I could imagine that problems occur if MIRO is installed both for a single user and for all users at the same time. But if you have always installed for one user, the problem will be somewhere else. Is there even a GAMS MIRO folder in the path you mentioned or is there only the GAMS MIRO entry in the "Apps & features" list?

**Comment by yordiak** [comment] 2020-08-04 16:02
Now it is only on "Apps & features" list. But before that, was on both (I forced an uninstall process and I installed it again)

**Comment by fproske** [comment] 2020-09-17 08:56
Hm. This seems weird and I'm not sure what could cause this. My guess is also that some "Install for all users"/"Install only for me" installations got somehow mixed up in the registry or some previous installation was not properly uninstalled. We could not reproduce this on our end and did not yet receive similar complains. We will keep on eye on this, but I will close this for time being.

**Closed as completed by fproske** 2020-09-17 08:56 UTC
